### ISSUE TITLE
I cannot get the same performance with the demo

### ISSUE THREAD

**Issue by hh6666** [cxcxcxcx/imgwarp-opencv#1]
![image](https://cloud.githubusercontent.com/assets/13196910/17402490/1b5869be-5a86-11e6-9480-24cc8f7e679e.png)
This is the performance of the demo.
![image](https://cloud.githubusercontent.com/assets/13196910/17402497/2a1e87da-5a86-11e6-99a8-24bda793dd38.png)
And this is my result. I wonder why this happen. I use the rigid transformation.

**Comment by ghost** [comment]
what file to run ... ? actually i am MS maths student dont know much about coding so tell me how to run it ? it is c++ file ?

**Comment by cxcxcxcx** [comment]
> what file to run ... ? actually i am MS maths student dont know much about coding so tell me how to run it ? it is c++ file ?

For this you would need cmake and OpenCV installed. Otherwise you can just try the JS version https://github.com/cxcxcxcx/imgwarp-js

**Comment by cxcxcxcx** [comment]
> And this is my result. I wonder why this happen. I use the rigid transformation.

If you write your own code, you need to debug yourself :) If you find a bug in the JS version, please file issues at https://github.com/cxcxcxcx/imgwarp-js . Thanks!
