### ISSUE TITLE
关于imgwarp_piecewiseaffine变换无效的问题

### ISSUE THREAD

**Issue by Flame-shi** [cxcxcxcx/imgwarp-opencv#12]
博主您好，请问我在调用c++的ImgWarp_PieceWiseAffine类别进行仿射变换时 输出一直是空白（255），是怎么回事呢。使用刚性变换ImgWarp_MLS_Rigid和相似变换ImgWarp_MLS_Similarity没问题。您的网页测试默认用的是仿射变换吗
以下是平移10(试了一下其他控制点仿射变换也不行，但是其他两个模型可以）
	ImgWarp_MLS* mls = new ImgWarp_PieceWiseAffine();
	mls->gridSize = 10;
	mls->alpha = 1;

	srcPointVec.emplace_back(0, 10);
	srcPointVec.emplace_back(0, 110);
	srcPointVec.emplace_back(100, 10);
	srcPointVec.emplace_back(100, 110);

	dstPointVec.emplace_back(0, 0);
	dstPointVec.emplace_back(0, 100);
	dstPointVec.emplace_back(100, 0);
	dstPointVec.emplace_back(100, 100);

	Mat result = mls->setAllAndGenerate(srcImg, srcPointVec, dstPointVec, srcImg.cols, srcImg.rows, 1);

**Comment by cxcxcxcx** [comment]
时间太久了，我也不记得了，不好意思哈。祝你好运！

**Comment by cxcxcxcx** [comment]
抱歉，近期没有时间维护/debug这个repo，麻烦您自己debug了

**Comment by Flame-shi** [comment]
> 抱歉，近期没有时间维护/debug这个repo，麻烦您自己debug了

好的，谢谢，祝工作顺利！
