### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by kurff** [cxcxcxcx/imgwarp-opencv#2]
double *w = new double[nPoint];

    rDx.create(tarH, tarW);
    rDy.create(tarH, tarW);

    if (nPoint < 2) {
        rDx.setTo(0);
        rDy.setTo(0);
        return;  // do not release the memory of w
}

**Comment by lz89** [comment]
This can be resolved by moving `double* w = new double[nPoint];` after the if condition.

**Comment by cxcxcxcx** [comment]
Sorry for the delay. This should be fixed now
