### ISSUE TITLE
Why I cannot find cv.h file??

### ISSUE THREAD

**Issue by emma-sjwang** [cxcxcxcx/imgwarp-opencv#4]
I have installed opencv3.1.0 in mu ubuntu 16.04.
I can import cv2 normally in python.
However, when I tried to compile these files using cmake 
```
mkdir build
cd build
cmake ../src/
make
```
the precedure cmake is correct.
But make occures error, that cannot find cv.h in src/delaunay.h file.
Please help me .
I want to use these image warping method as my image preprocessing procedure. And I don't know how to import it into my python program.

**Comment by prasadvagdargi** [comment]
This project uses old modules (last commit was 7 years ago) and is deprecated. Lots of the header files and modules were removed since then.
